language: java

jdk:
  - openjdk11

env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  directories:
    - .autoconf
    - $TRAVIS_HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - mvn clean package -Prelease -Ddebug.info=true -U -B $MAVEN_OPTS
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn clean package sonar:sonar -DsurefireArgs=-Dspring.profiles.active=ASYNCHRONOUS,TEST -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -B $MAVEN_OPTS; fi

after_success:
  - docker build -t openwms/org.openwms.common.comm:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
