eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: "!ASYNCHRONOUS"

server:
  port: ${owms.driver.server.port-rest}

---
spring:
  profiles: ASYNCHRONOUS
  main:
    web-environment: false

owms:
  driver:
    locu:
      queue-name: locu
    req:
      queue-name: req
    res:
      queue-name: res
      exchange-mapping: res.*
    sysu:
      queue-name: sysu
    upd:
      queue-name: upd
