eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: "!ASYNCHRONOUS"

server:
  port: ${owms.driver.connections.port-rest}

---
spring:
  profiles: ASYNCHRONOUS
  main:
    web-environment: false

owms:
  driver:
    osip:
      err:
        exchange-name: osip
        queue-name: err
        routing-key: tcpip-driver
      locu:
        exchange-name: osip
        routing-key: osip.locu.received
      req:
        exchange-name: osip
        routing-key: osip.req.received
      res:
        exchange-name: osip
        queue-name: res
        routing-key: tcpip-driver
      sysu:
        exchange-name: osip
        routing-key: osip.sysu.received
      upd:
        exchange-name: osip
        routing-key: osip.upd.received
